### ISSUE TITLE
Missing PNG files in the dataset (1-cell_image_library/dataset/train/train_x)

### ISSUE THREAD

**Issue by slitvinov** [KevinCortacero/KartezioPaper#1]
The directories  `1-cell_image_library/dataset/train/train_x` and `1-cell_image_library/dataset/train/train_x` in the [dataset](https://figshare.com/s/251b1f7cc55e6600826f) are empty. It seems the code is expecting PNG files in these locations.

```:; pwd
/home/lisergey/KartezioPaper/1-cil
:; python train_model.py
/usr/lib/python3/dist-packages/paramiko/transport.py:220: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
[Kartezio - INFO] -  42 nodes registered.
[Kartezio - INFO] -  5 metrics registered.
[Kartezio - INFO] -  7 fitness registered.
[Kartezio - INFO] -  7 endpoints registered.
[Kartezio - INFO] -  5 stackers registered.
[ WARN:0@0.673] global loadsave.cpp:241 findDecoder imread_('dataset/train/train_x/000_img.png'): can't open/read file: check file path/integrity```

**Comment by KevinCortacero** [comment]
Dear @slitvinov,
thank you for your feedback. The Cellpose dataset can be downloaded directly from the [cellpose website](https://www.cellpose.org/dataset) of the authors.
I will update the README file to avoid future confusion.
